# Reference guide: https://dzone.com/articles/how-to-dockerize-a-react-app-with-vite
services:
  #contains all container definitions
  frontend:
    build: .
    ports:
      - "5173:5173" #host port on the left, container port on the right. port 5173 used for vite
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3000:3000" #port 3000 used for express server. previously was 5000 but changed to 3000 to avoid conflict with MacOS Systems.
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost:5173
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

    # write the following command in the CLI to start docker.
    # docker compose up
